import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import PatientCard from './PatientCard';
import TaskList from './TaskList';

const Dashboard = ({ 
  user, 
    patients, 
      todaysTasks, 
        tomorrowsTasks, 
          onLogout, 
            onAddPatient 
            }) => {
              const [searchTerm, setSearchTerm] = useState('');
                const navigate = useNavigate();
                  
                    // Filter patients based on user's role and search term
                      const filteredPatients = patients.filter(patient => {
                          // Role-based filtering
                              if (user.role === 'Resident') {
                                    if (!user.assignedPatients.includes(patient.id)) {
                                            return false;
                                                  }
                                                      }
                                                          
                                                              // Search term filtering
                                                                  if (searchTerm) {
                                                                        return (
                                                                                patient.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                                                                                        patient.diagnosis.toLowerCase().includes(searchTerm.toLowerCase()) ||
                                                                                                patient.location.toLowerCase().includes(searchTerm.toLowerCase())
                                                                                                      );
                                                                                                          }
                                                                                                              
                                                                                                                  return true;
                                                                                                                    });

                                                                                                                      return (
                                                                                                                          <div className="dashboard">
                                                                                                                                <header className="dashboard-header">
                                                                                                                                        <h1>EMR Dashboard</h1>
                                                                                                                                                <div className="user-info">
                                                                                                                                                          <span>Welcome, {user.name} ({user.role})</span>
                                                                                                                                                                    <button onClick={onLogout} className="logout-button">Logout</button>
                                                                                                                                                                            </div>
                                                                                                                                                                                  </header>
                                                                                                                                                                                        
                                                                                                                                                                                              <div className="dashboard-content">
                                                                                                                                                                                                      <aside className="task-panels">
                                                                                                                                                                                                                <div className="task-panel">
                                                                                                                                                                                                                            <h3>Today's Shift Tasks 📋</h3>
                                                                                                                                                                                                                                        <TaskList tasks={todaysTasks} />
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                      <div className="task-panel">
                                                                                                                                                                                                                                                                                  <h3>Tomorrow's Day Work 📆</h3>
                                                                                                                                                                                                                                                                                              <TaskList tasks={tomorrowsTasks} />
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                </aside>
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                <main className="patients-section">
                                                                                                                                                                                                                                                                                                                                          <div className="patients-header">
                                                                                                                                                                                                                                                                                                                                                      <h2>Admitted Patients</h2>
                                                                                                                                                                                                                                                                                                                                                                  <div className="controls">
                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Search patients..."
                                                                                                                                                                                                                                                                                                                                                                                                                                value={searchTerm}
                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setSearchTerm(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="search-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => navigate('/add-patient')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="add-patient-button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          + Add Patient
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="patients-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {filteredPatients.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filteredPatients.map(patient => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <PatientCard key={patient.id} patient={patient} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="no-patients-message">No patients found.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Dashboard;