import React from 'react';
import { Link } from 'react-router-dom';

const TaskList = ({ tasks, onUpdateStatus }) => {
  const getStatusColor = (status) => {
      switch (status) {
            case 'Pending':
                    return '#FFD700'; // Yellow
                          case 'In Progress':
                                  return '#1E90FF'; // Blue
                                        case 'Completed':
                                                return '#32CD32'; // Green
                                                      default:
                                                              return 'gray';
                                                                  }
                                                                    };

                                                                      const getStatusIcon = (status) => {
                                                                          switch (status) {
                                                                                case 'Pending':
                                                                                        return '🟡';
                                                                                              case 'In Progress':
                                                                                                      return '🔵';
                                                                                                            case 'Completed':
                                                                                                                    return '🟢';
                                                                                                                          default:
                                                                                                                                  return '⚪';
                                                                                                                                      }
                                                                                                                                        };

                                                                                                                                          return (
                                                                                                                                              <div className="task-list">
                                                                                                                                                    {tasks.length > 0 ? (
                                                                                                                                                            tasks.map(task => (
                                                                                                                                                                      <div key={task.id} className="task-item">
                                                                                                                                                                                  <div 
                                                                                                                                                                                                className="task-status" 
                                                                                                                                                                                                              style={{ backgroundColor: getStatusColor(task.status) }}
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                        {getStatusIcon(task.status)}
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                            <div className="task-content">
                                                                                                                                                                                                                                                                                          <div className="task-header">
                                                                                                                                                                                                                                                                                                          <h4>{task.name}</h4>
                                                                                                                                                                                                                                                                                                                          {task.urgency && (
                                                                                                                                                                                                                                                                                                                                            <span className="urgency-flag">URGENT</span>
                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                      <p className="task-description">{task.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="task-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="task-patient">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link to={`/patient/${task.patientId}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Patient #{task.patientId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={task.status} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => onUpdateStatus(task.id, e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="task-status-dropdown"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="Pending">Pending</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="In Progress">In Progress</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Completed">Completed</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="no-tasks-message">No tasks available.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default TaskList;