// App.js - Main application file
import React, { useState } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import './App.css';

// Components
import Login from './components/Login';
import Dashboard from './components/Dashboard';
import PatientProfile from './components/PatientProfile';
import NewPatient from './components/NewPatient';

// Sample data
import { users, patients, tasks } from './data/sampleData';

function App() {
  const [currentUser, setCurrentUser] = useState(null);
    const [patientsData, setPatientsData] = useState(patients);
      const [tasksData, setTasksData] = useState(tasks);
        
          const handleLogin = (email, password) => {
              const user = users.find(u => u.email === email && u.password === password);
                  if (user) {
                        setCurrentUser(user);
                              return true;
                                  }
                                      return false;
                                        };
                                          
                                            const handleLogout = () => {
                                                setCurrentUser(null);
                                                  };
                                                    
                                                      const addPatient = (patient) => {
                                                          const newPatient = {
                                                                ...patient,
                                                                      id: patientsData.length + 1,
                                                                            tasks: [],
                                                                                  active: true
                                                                                      };
                                                                                          setPatientsData([...patientsData, newPatient]);
                                                                                            };
                                                                                              
                                                                                                const addTask = (task) => {
                                                                                                    const newTask = {
                                                                                                          ...task,
                                                                                                                id: tasksData.length + 1,
                                                                                                                      status: 'Pending'
                                                                                                                          };
                                                                                                                              setTasksData([...tasksData, newTask]);
                                                                                                                                  
                                                                                                                                      // Update patient's tasks
                                                                                                                                          const updatedPatients = patientsData.map(patient => {
                                                                                                                                                if (patient.id === task.patientId) {
                                                                                                                                                        return {
                                                                                                                                                                  ...patient,
                                                                                                                                                                            tasks: [...patient.tasks, newTask.id]
                                                                                                                                                                                    };
                                                                                                                                                                                          }
                                                                                                                                                                                                return patient;
                                                                                                                                                                                                    });
                                                                                                                                                                                                        setPatientsData(updatedPatients);
                                                                                                                                                                                                          };
                                                                                                                                                                                                            
                                                                                                                                                                                                              const updateTaskStatus = (taskId, status) => {
                                                                                                                                                                                                                  const updatedTasks = tasksData.map(task => {
                                                                                                                                                                                                                        if (task.id === taskId) {
                                                                                                                                                                                                                                return { ...task, status };
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                            return task;
                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                    setTasksData(updatedTasks);
                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          const dischargePatient = (patientId) => {
                                                                                                                                                                                                                                                              const updatedPatients = patientsData.map(patient => {
                                                                                                                                                                                                                                                                    if (patient.id === patientId) {
                                                                                                                                                                                                                                                                            return { ...patient, active: false };
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                        return patient;
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                setPatientsData(updatedPatients);
                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      const getPatientTasks = (patientId) => {
                                                                                                                                                                                                                                                                                                          return tasksData.filter(task => task.patientId === patientId);
                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                const getTodaysTasks = () => {
                                                                                                                                                                                                                                                                                                                    const today = new Date().toISOString().split('T')[0];
                                                                                                                                                                                                                                                                                                                        return tasksData.filter(task => 
                                                                                                                                                                                                                                                                                                                              task.dueDate === today || 
                                                                                                                                                                                                                                                                                                                                    (task.urgency && task.status !== 'Completed')
                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                              const getTomorrowsTasks = () => {
                                                                                                                                                                                                                                                                                                                                                  const tomorrow = new Date();
                                                                                                                                                                                                                                                                                                                                                      tomorrow.setDate(tomorrow.getDate() + 1);
                                                                                                                                                                                                                                                                                                                                                          const tomorrowStr = tomorrow.toISOString().split('T')[0];
                                                                                                                                                                                                                                                                                                                                                              return tasksData.filter(task => 
                                                                                                                                                                                                                                                                                                                                                                    task.dueDate === tomorrowStr && 
                                                                                                                                                                                                                                                                                                                                                                          !task.urgency &&
                                                                                                                                                                                                                                                                                                                                                                                task.status !== 'Completed'
                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                              <Router>
                                                                                                                                                                                                                                                                                                                                                                                                    <div className="app">
                                                                                                                                                                                                                                                                                                                                                                                                            <Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                      <Route 
                                                                                                                                                                                                                                                                                                                                                                                                                                  path="/login" 
                                                                                                                                                                                                                                                                                                                                                                                                                                              element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentUser ? 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Navigate to="/dashboard" /> : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Login onLogin={handleLogin} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Route 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        path="/dashboard" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currentUser ? 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Dashboard 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    user={currentUser}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      patients={patientsData.filter(p => p.active)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        todaysTasks={getTodaysTasks()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tomorrowsTasks={getTomorrowsTasks()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onLogout={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onAddPatient={addPatient}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /> : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Navigate to="/login" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Route 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          path="/patient/:id" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currentUser ? 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <PatientProfile 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user={currentUser}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        patients={patientsData}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          getPatientTasks={getPatientTasks}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onAddTask={addTask}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onUpdateTaskStatus={updateTaskStatus}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onDischarge={dischargePatient}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /> : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Navigate to="/login" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Route 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            path="/add-patient" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      currentUser ? 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <NewPatient 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        user={currentUser}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onAddPatient={addPatient}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /> : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Navigate to="/login" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route path="/" element={<Navigate to="/login" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Router>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;